# Generated by Django 2.1.5 on 2019-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_preview',
            field=models.ImageField(default=1, upload_to='News/previews'),
            preserve_default=False,
        ),
    ]
