# Generated by Django 2.1.5 on 2019-03-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_post_img_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_preview',
            field=models.ImageField(blank=True, upload_to='News/previews'),
        ),
    ]
