# Generated by Django 2.1.5 on 2019-05-21 06:08

from django.db import migrations, models
import validatedfile.fields


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20190302_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_preview',
            field=models.ImageField(blank=True, null=True, upload_to='News/previews', verbose_name='Превью новости:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Текст статьи:'),
        ),
    ]
