# Generated by Django 2.1.5 on 2019-05-22 09:21

from django.db import migrations
import validatedfile.fields


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20190521_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachments',
            new_name='attachments0',
        ),
        migrations.AddField(
            model_name='post',
            name='attachments1',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments2',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments3',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments4',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments5',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments6',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments7',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments8',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments9',
            field=validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
