# Generated by Django 2.1.5 on 2019-05-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20190522_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachments0',
            new_name='attach0',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments1',
            new_name='attach1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments2',
            new_name='attach2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments3',
            new_name='attach3',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments4',
            new_name='attach4',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments5',
            new_name='attach5',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments6',
            new_name='attach6',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments7',
            new_name='attach7',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments8',
            new_name='attach8',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachments9',
            new_name='attach9',
        ),
    ]
