# Generated by Django 2.1.5 on 2019-05-23 09:32

from django.db import migrations, models
import django.db.models.deletion
import validatedfile.fields


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_auto_20190522_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att', validatedfile.fields.ValidatedFileField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach0',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attach9',
        ),
        migrations.AddField(
            model_name='attachment',
            name='apost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='News.Post'),
        ),
    ]
